### ISSUE TITLE
tempo2 dependency

### ISSUE THREAD

**Issue by astrolamb** [astrolamb/ceffyl#27]
Tempo2 is causing an issue with installation. Work is being done to remove tempo2 dependency as a result of dependency on enterprise

Issues cause: cannot directly pip or conda install ceffyl

**Comment by vhaasteren** [comment]
As a workaround, you can install enterprise without dependencies in the setup.py of ceffyl. Then don't list it in the requirements.txt. Its a bit clunky, but it does exactly what you want until Enterprise lifts the tempo2 dependency. You would do it with a PostInstallCommand in the setup.py:

```
class PostInstallCommand(install):
    """Post-installation for installation mode."""
    def run(self):
        install.run(self)
        # Install enterprise without dependencies
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '--no-deps', 'enterprise-pulsar'])
```

Then, as an argument to setup in the setup.py, you would pass:

```
    cmdclass={
        'install': PostInstallCommand,
    },
```

**Comment by astrolamb** [comment]
Thanks @vhaasteren!

I've added this piece but unfortunately, I'm getting this error

```
File "/Users/lambwg/Applications/miniconda3/envs/ptarcade/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/lambwg/Applications/miniconda3/envs/ptarcade/bin/python3.10', '-m', 'pip', 'install', '--no-deps', 'enterprise-pulsar']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ceffyl
Failed to build ceffyl
ERROR: Could not build wheels for ceffyl, which is required to install pyproject.toml-based projects
```

Do you know what's going on?

**Comment by vhaasteren** [comment]
Are you able to run the install command yourself on the command line? The above message doesn't give the output of the pip install command

**Comment by astrolamb** [comment]
Yes, `python -m pip install --no-deps enterprise-pulsar` worked on my mac

**Comment by astrolamb** [comment]
This is the full error message - I can't find a solution. The install seemingly can't find pip... For now, I'm just removing the enterprise requirement from ceffyl and asking that users use the [above command](https://github.com/astrolamb/ceffyl/issues/27#issuecomment-1853630367) after installation.

```
      Traceback (most recent call last):
        File "/Users/lambwg/Applications/miniconda3/envs/test3/bin/pip", line 6, in <module>
          from pip._internal.cli.main import main
      ModuleNotFoundError: No module named 'pip'
      Traceback (most recent call last):
        File "/Users/lambwg/Applications/miniconda3/envs/test3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/lambwg/Applications/miniconda3/envs/test3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/lambwg/Applications/miniconda3/envs/test3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/6x/sxrld4757klfbx01v7hgm5dc0000gs/T/pip-build-env-1ggz4cus/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
        File "/private/var/folders/6x/sxrld4757klfbx01v7hgm5dc0000gs/T/pip-build-env-1ggz4cus/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/6x/sxrld4757klfbx01v7hgm5dc0000gs/T/pip-build-env-1ggz4cus/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 21, in <module>
        File "/private/var/folders/6x/sxrld4757klfbx01v7hgm5dc0000gs/T/pip-build-env-1ggz4cus/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/6x/sxrld4757klfbx01v7hgm5dc0000gs/T/pip-build-env-1ggz4cus/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/6x/sxrld4757klfbx01v7hgm5dc0000gs/T/pip-build-env-1ggz4cus/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/6x/sxrld4757klfbx01v7hgm5dc0000gs/T/pip-build-env-1ggz4cus/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/6x/sxrld4757klfbx01v7hgm5dc0000gs/T/pip-build-env-1ggz4cus/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/6x/sxrld4757klfbx01v7hgm5dc0000gs/T/pip-build-env-1ggz4cus/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/6x/sxrld4757klfbx01v7hgm5dc0000gs/T/pip-build-env-1ggz4cus/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 403, in run
          self.run_command("install")
        File "/private/var/folders/6x/sxrld4757klfbx01v7hgm5dc0000gs/T/pip-build-env-1ggz4cus/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/6x/sxrld4757klfbx01v7hgm5dc0000gs/T/pip-build-env-1ggz4cus/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/6x/sxrld4757klfbx01v7hgm5dc0000gs/T/pip-build-env-1ggz4cus/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 17, in run
        File "/Users/lambwg/Applications/miniconda3/envs/test3/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/Users/lambwg/Applications/miniconda3/envs/test3/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['pip', 'install', '--no-deps', 'enterprise-pulsar']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ceffyl
Failed to build ceffyl
ERROR: Could not build wheels for ceffyl, which is required to install pyproject.toml-based projects
```

**Comment by astrolamb** [comment]
This has now been fixed by @davecwright3 (thank you!!)
